# generated by datamodel-codegen:
#   filename:  clase-tareas.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, conint

from . import comunes_schema


class ClaseTareas(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uid: str
    titulo: str
    descripcion_complejidad: str = Field(
        ..., description='Qué hace a esta clase más compleja que la anterior.'
    )
    ficha_md: str | None = Field(
        None,
        description='Ficha de diseño instruccional del tema, para el instructor: objetivos por ruta, métodos de evaluación, efectos por componente, matriz de diferenciación y plan de implementación. El aula no la muestra.',
    )
    orden: conint(ge=1)
    objetivos: list[str] = Field(..., description='Códigos de objetivo, p. ej. OB-3.')
    diseno: comunes_schema.Diseno
