# generated by datamodel-codegen:
#   filename:  comunes.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint


class Comunes(RootModel[Any]):
    root: Any = Field(..., title='Comunes')


class EfectoId(StrEnum):
    ejemplo_resuelto = 'ejemplo_resuelto'
    problema_completar = 'problema_completar'
    modalidad = 'modalidad'
    variabilidad = 'variabilidad'
    elementos_aislados = 'elementos_aislados'
    redundancia = 'redundancia'
    atencion_dividida = 'atencion_dividida'
    informacion_transitoria = 'informacion_transitoria'
    interactividad_elementos = 'interactividad_elementos'
    movimiento_humano = 'movimiento_humano'
    auto_gestion = 'auto_gestion'
    auto_explicacion = 'auto_explicacion'
    imaginacion = 'imaginacion'
    solucion_libre = 'solucion_libre'
    memoria_colectiva = 'memoria_colectiva'
    desvanecimiento_guia = 'desvanecimiento_guia'
    reversion_experiencia = 'reversion_experiencia'


class Componente(StrEnum):
    tarea = 'tarea'
    soporte = 'soporte'
    procedimental = 'procedimental'
    practica_parcial = 'practica_parcial'
    evaluacion = 'evaluacion'


class NivelApoyo(StrEnum):
    ejemplo_resuelto = 'ejemplo_resuelto'
    por_completar = 'por_completar'
    convencional = 'convencional'
    solucion_libre = 'solucion_libre'


class Interactividad(StrEnum):
    baja = 'baja'
    media = 'media'
    alta = 'alta'


class Lenguaje(StrEnum):
    c = 'c'
    cpp = 'cpp'
    python = 'python'


class EfectoAplicado(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: EfectoId
    como: str = Field(..., description='Una frase: cómo se aplicó el efecto.')


class Arcs(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    atencion: str
    relevancia: str
    confianza: str
    satisfaccion: str


class Diseno(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    paso_clt4bp: conint(ge=1, le=10)
    componente: Componente
    efectos: list[EfectoAplicado]
    interactividad: Interactividad
    tiempo_estimado_min: conint(ge=1)
    justificacion: str
    advertencias: list[str]


class CasoPrueba(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    entrada: str = Field(..., description='Texto que recibe el programa por stdin.')
    salida_esperada: str
    oculto: bool
