# generated by datamodel-codegen:
#   filename:  diseno-curso.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict

from . import (
    clase_tareas_schema,
    comunes_schema,
    info_procedimental_schema,
    info_soporte_schema,
    medio_schema,
    objetivo_schema,
    practica_parcial_schema,
    tarea_schema,
    variante_schema,
)


class Grupo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    clave: str
    nombre: str
    nivel: str | None


class Curso(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: int
    titulo: str
    lenguaje: comunes_schema.Lenguaje
    grupos: list[Grupo]


class DisenoCurso(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    curso: Curso
    objetivos: list[objetivo_schema.Objetivo]
    clases: list[clase_tareas_schema.ClaseTareas]
    tareas: list[tarea_schema.Tarea]
    soporte: list[info_soporte_schema.InfoSoporte]
    procedimental: list[info_procedimental_schema.InfoProcedimental]
    practica_parcial: list[practica_parcial_schema.PracticaParcial]
    variantes: list[variante_schema.Variante]
    medios: list[medio_schema.Medio]
