# generated by datamodel-codegen:
#   filename:  index.schema.json

from __future__ import annotations

from pydantic import BaseModel

from . import (
    clase_tareas_schema,
    diseno_curso_schema,
    info_procedimental_schema,
    info_soporte_schema,
    medio_schema,
    objetivo_schema,
    practica_parcial_schema,
    tarea_schema,
    variante_schema,
)


class Contratos(BaseModel):
    objetivo: objetivo_schema.Objetivo | None = None
    clase: clase_tareas_schema.ClaseTareas | None = None
    tarea: tarea_schema.Tarea | None = None
    soporte: info_soporte_schema.InfoSoporte | None = None
    procedimental: info_procedimental_schema.InfoProcedimental | None = None
    practica_parcial: practica_parcial_schema.PracticaParcial | None = None
    variante: variante_schema.Variante | None = None
    medio: medio_schema.Medio | None = None
    diseno: diseno_curso_schema.DisenoCurso | None = None
