# generated by datamodel-codegen:
#   filename:  info-soporte.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

from . import comunes_schema


class Tipo(StrEnum):
    modelo_mental = 'modelo_mental'
    sap = 'sap'
    explicacion = 'explicacion'
    mapa_conceptual = 'mapa_conceptual'
    guion_video = 'guion_video'


class InfoSoporte(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uid: str
    clase_uid: str
    tipo: Tipo
    titulo: str
    cuerpo_md: str = Field(
        ..., description='Markdown; diagramas en bloques ```mermaid.'
    )
    diseno: comunes_schema.Diseno
