# generated by datamodel-codegen:
#   filename:  info-procedimental.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field

from . import comunes_schema


class Tipo(StrEnum):
    ficha_sintaxis = 'ficha_sintaxis'
    guia_preguntas = 'guia_preguntas'
    errores_frecuentes = 'errores_frecuentes'
    ejemplo_isomorfico = 'ejemplo_isomorfico'
    protocolo_verbal = 'protocolo_verbal'


class InfoProcedimental(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uid: str
    tarea_uid: str | None = Field(
        None,
        description='Tarea a la que ayuda (ayuda justo a tiempo de una sola tarea). Lleva tarea_uid o clase_uid, no ambos.',
    )
    clase_uid: str | None = Field(
        None,
        description='Clase (tema) a la que pertenece: tarjeta de sintaxis, guía de rutina, errores frecuentes, ejemplo isomórfico o protocolo verbal del tema.',
    )
    tipo: Tipo
    titulo: str
    cuerpo_md: str
    diseno: comunes_schema.Diseno
