# generated by datamodel-codegen:
#   filename:  medio.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, confloat


class Tipo(StrEnum):
    imagen = 'imagen'
    audio = 'audio'
    video = 'video'
    protocolo_verbal = 'protocolo_verbal'


class Segmento(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    inicio_s: confloat(ge=0.0)
    etiqueta: str


class Medio(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uid: str
    tipo: Tipo
    titulo: str
    duracion_s: confloat(ge=0.0) | None
    segmentos: list[Segmento]
    transcripcion: str | None
