# generated by datamodel-codegen:
#   filename:  objetivo.schema.json

from __future__ import annotations

from enum import StrEnum

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Tipo(StrEnum):
    conocimiento = 'conocimiento'
    habilidad = 'habilidad'
    actitud = 'actitud'


class EvaluacionEnum(StrEnum):
    recall = 'recall'
    comprension = 'comprension'
    practica = 'practica'
    cis_imms = 'cis_imms'
    mslq = 'mslq'
    cs = 'cs'


class Objetivo(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uid: str
    codigo: constr(pattern=r'^OB-[0-9]+$')
    orden: conint(ge=1)
    descripcion: constr(min_length=10) = Field(
        ..., description='Verbo observable + condición + criterio.'
    )
    tipo: Tipo
    evaluacion: list[EvaluacionEnum] = Field(
        ..., description='Métodos con que se comprobará el objetivo.', min_length=1
    )
