# generated by datamodel-codegen:
#   filename:  practica-parcial.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field

from . import comunes_schema


class Ejercicio(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    enunciado_md: str
    solucion: str
    casos_prueba: list[comunes_schema.CasoPrueba]


class PracticaParcial(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uid: str
    habilidad: str = Field(
        ...,
        description="Subhabilidad que se automatiza, p. ej. 'declarar y recorrer arreglos'.",
    )
    lenguaje: comunes_schema.Lenguaje
    ejercicios: list[Ejercicio]
    diseno: comunes_schema.Diseno
