# generated by datamodel-codegen:
#   filename:  tarea.schema.json

from __future__ import annotations

from pydantic import BaseModel, ConfigDict, Field, conint, constr

from . import comunes_schema


class Tarea(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uid: str
    clase_uid: str
    orden: conint(ge=1)
    titulo: str
    nivel_apoyo: comunes_schema.NivelApoyo
    enunciado_md: str = Field(
        ..., description='Enunciado en Markdown, con el escenario auténtico.'
    )
    arcs: comunes_schema.Arcs
    lenguaje: comunes_schema.Lenguaje
    codigo_inicial: str = Field(
        ...,
        description="Vacío en convencional; solución comentada en ejemplo resuelto; con huecos '/* HUECO n: ... */' en por completar.",
    )
    solucion: str = Field(
        ...,
        description='Solución de referencia completa; debe pasar todos los casos de prueba.',
    )
    casos_prueba: list[comunes_schema.CasoPrueba]
    pide_autoexplicacion: bool
    colaborativa: bool
    rutas: list[constr(pattern=r'^G[0-9]+$')] | None = Field(
        [],
        description='Grupos (rutas) que trabajan esta tarea; vacío = todos. El estudiante solo ve las tareas de su ruta.',
    )
    diseno: comunes_schema.Diseno
