# generated by datamodel-codegen:
#   filename:  variante.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, constr


class Dimensione(StrEnum):
    contenido = 'contenido'
    proceso = 'proceso'
    producto = 'producto'


class Diferenciacion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    dimensiones: list[Dimensione] = Field(..., min_length=1)
    razon: str = Field(
        ..., description='Por qué este grupo necesita la variante (Tomlinson).'
    )


class Variante(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    uid: str
    elemento_uid: str
    grupo_clave: constr(pattern=r'^G[0-9]+$')
    cambios: dict[str, Any] = Field(
        ...,
        description='Campos del elemento base que cambian para este grupo. No puede cambiar identificadores, la posición, la solución ni los casos de prueba: todos los grupos se evalúan con el mismo criterio.',
    )
    diferenciacion: Diferenciacion
